export const DEFAULT_BUDGET = 1200;
export const DEFAULT_SHOW_BUDGET = 2000;
export const DEFAULT_LIMIT = 50;
export const DOC_LINE_WARNING_LIMIT = 150;
export const FRAGMENT_TOKEN_THRESHOLD = 180;
export const DUPLICATE_SIMILARITY_THRESHOLD = 0.72;
