import fs from "node:fs";
import path from "node:path";

import type { KnowledgeModel } from "./knowledge-model.js";
import type { KnowledgeWriteContext } from "./write-context.js";

/**
 * README navigation is a rebuildable, machine-managed region only. It is not a knowledge
 * node, never enters search, is not part of any document digest or validation evidence,
 * and must never expand the reviewed scope. The bytes outside the marked region are owned
 * by humans and are preserved verbatim.
 */

export const NAVIGATION_START = "<!-- llmdoc:navigation:start -->";
export const NAVIGATION_END = "<!-- llmdoc:navigation:end -->";

export function renderNavigation(model: KnowledgeModel): string {
  const lines = [
    NAVIGATION_START,
    "<!-- Generated by llmdoc from document titles, descriptions and paths; edit outside this region. -->",
    "",
    "# Knowledge map",
    ""
  ];
  const byTopic = new Map<string, typeof model.documents>();
  for (const document of model.documents) {
    const topic = document.topic ?? "";
    const bucket = byTopic.get(topic) ?? [];
    bucket.push(document);
    byTopic.set(topic, bucket);
  }
  const topics = [...byTopic.keys()].sort((left, right) => {
    if (left === right) return 0;
    if (left === "") return -1;
    if (right === "") return 1;
    return left.localeCompare(right);
  });
  for (const topic of topics) {
    if (topic !== "") {
      lines.push(`## ${escapeNavigationText(topic)}`, "");
    }
    for (const document of byTopic.get(topic)!) {
      const title = escapeNavigationText(document.title ?? document.id);
      const description = escapeNavigationText(document.frontmatter.description);
      const supersededBy = model.supersededBy.get(document.id) ?? [];
      const markers: string[] = [`\`${document.frontmatter.kind}\``];
      if (supersededBy.length > 0) {
        markers.push(`superseded by ${supersededBy.map((id) => `\`${id}\``).join(", ")}`);
      }
      lines.push(`- [${title}](docs/${document.id}) — ${description} (${markers.join("; ")})`);
    }
    lines.push("");
  }
  lines.push(NAVIGATION_END);
  return lines.join("\n");
}

export function readNavigationRegion(content: string): string | null {
  const start = content.indexOf(NAVIGATION_START);
  if (start === -1) {
    return null;
  }
  const end = content.indexOf(NAVIGATION_END, start + NAVIGATION_START.length);
  if (end === -1) {
    return null;
  }
  return content.slice(start, end + NAVIGATION_END.length);
}

export interface NavigationReplacement {
  content: string;
  changed: boolean;
}

/** Replaces only the marked region, preserving all human-managed bytes exactly. */
export function replaceNavigationRegion(existing: string | null, rendered: string): NavigationReplacement {
  if (existing === null || existing.length === 0) {
    const content = `# Knowledge Base\n\n${rendered}\n`;
    return { content, changed: true };
  }
  const region = readNavigationRegion(existing);
  if (region === null) {
    const separator = existing.endsWith("\n") ? "\n" : "\n\n";
    const content = `${existing}${separator}${rendered}\n`;
    return { content, changed: true };
  }
  const start = existing.indexOf(region);
  const content = `${existing.slice(0, start)}${rendered}${existing.slice(start + region.length)}`;
  return { content, changed: content !== existing };
}

export function readReadme(knowledgeRoot: string): string | null {
  const readmePath = path.join(knowledgeRoot, "README.md");
  try {
    return fs.readFileSync(readmePath, "utf8");
  } catch {
    return null;
  }
}

/** True when the worktree README's navigation region no longer matches the model. */
export function navigationChanged(context: KnowledgeWriteContext): boolean {
  const existing = readReadme(context.knowledge.worktreeRoot);
  return readNavigationRegion(existing ?? "") !== renderNavigation(context.worktreeModel);
}

/** Builds the desired README bytes from the observed README and the reviewed model. */
export function renderNavigationReadme(knowledgeRoot: string, model: KnowledgeModel): string {
  const existing = readReadme(knowledgeRoot);
  return replaceNavigationRegion(existing, renderNavigation(model)).content;
}

/**
 * Stable encoding for navigation text. It must never let a title or description
 * reproduce the machine markers (or other raw HTML) inside the rendered region,
 * otherwise a later rebuild would find an injected marker first and truncate or
 * duplicate the human-managed bytes outside the region.
 */
function escapeNavigationText(input: string): string {
  return input
    .replace(/\r?\n/g, " ")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("[", "\\[")
    .replaceAll("]", "\\]")
    .trim();
}
